name: exif_flutter
version: 0.0.1
author: Luca Romagnoli
description: Decode Exif data from jpeg files (Dart port based on https://github.com/exif-js/exif-js/)
homepage: 
environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  #sdk: '>=1.24.0 <2.0.0'
dependencies:
  http: '>=0.11.3+12'

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
#flutter: